---
- name: Main Playbook
  hosts: testing
  become: true

  roles:
    - role: system
      tags:
        - system

    - role: geerlingguy.security
      tags:
        - security

    - role: geerlingguy.firewall
      tags:
        - security

    - role: podman
      tags:
        - podman
      when: services is defined

    - role: containers
      tags:
        - containers
      when: services is defined
