hostname: '{{ inventory_hostname }}'

timezone: Europe/Berlin

service_config_root: /opt/services

services:
  - actual
  - traefik

#
# NFS
#
nfs_enabled: true

#
# SSH (geerlingguy.security)
#
security_sudoers_passwordless: ['ladmin']

security_autoupdate_reboot: true

security_autoupdate_reboot_time: '03:00'

security_autoupdate_mail_to: 'notify'

security_autoupdate_mail_on_error: false

security_fail2ban_enabled: false

#
# Firewall (geerlingguy.firewall)
#
firewall_allowed_tcp_ports:
  - '22'
  - '8080'
  - '8443'

firewall_forwarded_tcp_ports:
  - { src: '80', dest: '8080' }
  - { src: '443', dest: '8443' }

firewall_disable_firewalld: true

firewall_disable_ufw: true
