---
- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    autoremove: true
  when: ansible_os_family == 'Debian'

- name: Update and upgrade packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    update_only: true
  when: ansible_os_family == 'RedHat'

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: true
  when: ansible_os_family == 'RedHat'

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_os_family == 'Debian'

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when:
    - reboot_required_file.stat.exists
    - ansible_os_family == 'Debian'

- name: Set the hostname
  ansible.builtin.hostname:
    name: '{{ hostname }}'

- name: Replace the hostname entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: '127.0.0.1 {{ hostname }}'
    owner: root
    group: root
    mode: '0644'
