---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: Ensure nfs requirements are installed
  ansible.builtin.package:
    name: '{{ system_packages }}'
    state: present

- name: Ensure mount directories exist
  ansible.builtin.file:
    path: '/nfs/{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: '{{ secrets.shares }}'

- name: Mount nfs shares to directories
  ansible.posix.mount:
    src: '{{ secrets.networks.lan.base }}.10:/volume1/{{ item }}'
    path: '/nfs/{{ item }}'
    opts: defaults
    state: mounted
    fstype: nfs
  loop: '{{ secrets.shares }}'
