---
- name: Add entry to subuid file
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: '^containers:.*'
    line: 'containers:2147483647:2147483648'
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Add entry to subgid file
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: '^containers:.*'
    line: 'containers:2147483647:2147483648'
    create: true
    mode: '0644'
    owner: root
    group: root
