---
- name: Create container user
  ansible.builtin.user:
    name: '{{ secrets.users.container.name }}'
    password: !
    uid: '{{ secrets.users.container.uid }}'
    group: users
    shell: /bin/nologin
    groups:
      - users
    state: present
    append: true

- name: Enable lingering for container user
  ansible.builtin.command:
    cmd: 'loginctl enable-linger {{ secrets.users.container.name }}'
    creates: '/var/lib/systemd/linger/{{ secrets.users.container.name }}'

- name: Add entry to subuid file
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: '^containers:.*'
    line: 'containers:2147483647:2147483648'
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Add entry to subgid file
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: '^containers:.*'
    line: 'containers:2147483647:2147483648'
    create: true
    mode: '0644'
    owner: root
    group: root
